#
# Quick Setup Script for Financia Infrastructure
# Run this script to set up everything needed for GitHub Actions CI/CD
#

$ErrorActionPreference = "Stop"

Write-Host "================================================"
Write-Host "Financia Infrastructure Setup"
Write-Host "================================================"
Write-Host ""

# Step 1: Setup Workload Identity
Write-Host "Step 1: Setting up Workload Identity Federation..."
Write-Host "This will create:"
Write-Host "  - Workload Identity Pool and Provider"
Write-Host "  - Terraform service accounts (dev and prod)"
Write-Host "  - GCS bucket for Terraform state"
Write-Host "  - Artifact Registry repository"
Write-Host ""
Write-Host "Press Enter to continue or Ctrl+C to cancel..."
$null = Read-Host

& "$PSScriptRoot\setup-workload-identity.ps1"

Write-Host ""
Write-Host "================================================"
Write-Host "Step 2: Configure GitHub Secrets"
Write-Host "================================================"
Write-Host ""
Write-Host "Add the following secrets to GitHub:"
Write-Host "Repository -> Settings -> Secrets and variables -> Actions"
Write-Host ""
Write-Host "Infrastructure Secrets (from the output above):"
Write-Host "  - WIF_PROVIDER"
Write-Host "  - WIF_SA_EMAIL_DEV"
Write-Host "  - WIF_SA_EMAIL_PROD"
Write-Host "  - GCP_PROJECT_ID"
Write-Host "  - GCS_TERRAFORM_STATE_BUCKET"
Write-Host ""
Write-Host "Application Secrets:"
Write-Host "  - WHATSAPP_API_KEY"
Write-Host "  - GEMINI_API_KEY"
Write-Host "  - GOOGLE_CLIENT_ID"
Write-Host "  - GOOGLE_CLIENT_SECRET"
Write-Host "  - GOOGLE_REFRESH_TOKEN"
Write-Host "  - WHATSAPP_WEBHOOK_VERIFY_TOKEN"
Write-Host "  - SPREADSHEET_ID_DEV"
Write-Host "  - SPREADSHEET_ID_PROD"
Write-Host ""
Write-Host "Press Enter after you've added the secrets..."
$null = Read-Host

Write-Host ""
Write-Host "================================================"
Write-Host "Step 3: Configure GitHub Environments"
Write-Host "================================================"
Write-Host ""
Write-Host "Create two environments in GitHub:"
Write-Host "Repository -> Settings -> Environments"
Write-Host ""
Write-Host "1. Create 'dev' environment (no protection rules)"
Write-Host "2. Create 'prod' environment (add required reviewers)"
Write-Host ""
Write-Host "Press Enter after you've created the environments..."
$null = Read-Host

Write-Host ""
Write-Host "================================================"
Write-Host "Step 4: Test Terraform Locally (Optional)"
Write-Host "================================================"
Write-Host ""
Write-Host "To test Terraform setup locally:"
Write-Host ""
Write-Host "  cd terraform"
Write-Host "  terraform init -backend-config=environments/dev/backend.hcl"
Write-Host "  terraform validate"
Write-Host "  terraform plan -var-file=environments/dev/terraform.tfvars ``"
Write-Host "    -var=`"project_id=dev-ai-agents-projects`" ``"
Write-Host "    -var=`"whatsapp_api_key=`$env:WHATSAPP_API_KEY`" ``"
Write-Host "    -var=`"gemini_api_key=`$env:GEMINI_API_KEY`" ``"
Write-Host "    -var=`"google_client_id=`$env:GOOGLE_CLIENT_ID`" ``"
Write-Host "    -var=`"google_client_secret=`$env:GOOGLE_CLIENT_SECRET`" ``"
Write-Host "    -var=`"google_refresh_token=`$env:GOOGLE_REFRESH_TOKEN`" ``"
Write-Host "    -var=`"spreadsheet_id=`$env:SPREADSHEET_ID`" ``"
Write-Host "    -var=`"whatsapp_webhook_verify_token=`$env:WEBHOOK_TOKEN`""
Write-Host ""

Write-Host "================================================"
Write-Host "Setup Complete!"
Write-Host "================================================"
Write-Host ""
Write-Host "Next Steps:"
Write-Host "1. Create a test PR to trigger terraform plan"
Write-Host "2. Review the plan output in the PR comment"
Write-Host "3. Merge the PR"
Write-Host "4. Manually trigger Terraform Apply workflow"
Write-Host ""
Write-Host "For detailed instructions, see:"
Write-Host "  docs/INFRASTRUCTURE_SETUP.md"
Write-Host ""
